### ISSUE TITLE
Remaining tasks split by releases

### ISSUE THREAD

**Issue by nop33** [alephium/mobile-wallet#12]
### Design
- [x] Design wallet import screen
- [x] Design settings screen
- [x] Design address create/edit screen
- [x] Design "send" screen
- [x] Design "receive" screen
- [x] Design transaction details modal
- [x] Design security screen (phrase backup etc.)

### Code
- [ ] Improve wallet import screen
- [x] Implement settings screen
- [x] Implement address create/edit screen
- [x] ❓ Display addresses in dashboard screen _(comment on Figma says this is not needed)_
- [x] Implement "qr code" screen/modal
- [x] Implement "make address main" star button
- [x] Implement transaction details modal

## Release 2

_based on https://github.com/alephium/mobile-wallet/issues/1#issuecomment-1087470445_

- [x] Display assets/tokens in dashboard screen
- [ ] Implement chart in dashboard screen
- [ ] Implement asset/token details screen
