### ISSUE TITLE
Android Wallet Bugs

### ISSUE THREAD

**Issue by ErgoTester** [alephium/mobile-wallet#320]
- [x] alephium/mobile-wallet#324
- [x] alephium/mobile-wallet#325
- [x] alephium/mobile-wallet#321
- [x] alephium/mobile-wallet#323
- [x] alephium/mobile-wallet#322
- [ ] alephium/alephium-frontend#52
- [x] wallet connect isn't connecting , tried with ayin and deardare ( pc ) the wallet scan the qr than goes the home page , no message no warning no connection
- [x] alephium/mobile-wallet#337
- [ ] alephium/alephium-frontend#101
- [ ] alephium/alephium-frontend#102
- [ ] alephium/alephium-frontend#103
- [ ] alephium/alephium-frontend#104
- [x] alephium/mobile-wallet#375
- [x] alephium/mobile-wallet#376
- [x] alephium/mobile-wallet#377
- [ ] alephium/alephium-frontend#105
- [x] alephium/mobile-wallet#380
- [x] alephium/mobile-wallet#378
- [ ] alephium/alephium-frontend#106

**Comment by mvaivre** [comment]
Hey there! Thanks for your report.
Could you specify which version of Android you are using? Thanks.

**Comment by ErgoTester** [comment]
android 13

**Comment by nop33** [comment]
>  address settings , can't set default address

Hey @ErgoTester, thank you for your reports!

Could you please elaborate on this one? What are the steps to reproduce? I've tested the default address setting feature and it works as expected. If what you mean is that the toggle is disabled when you have only 1 address, that's expected

<img width="351" alt="image" src="https://github.com/alephium/mobile-wallet/assets/1579899/ea4c7f92-3e86-4648-a20a-1848238f60fb">

**Comment by ErgoTester** [comment]
created an extra address , in this address setting i toggled default address but it doesn't makes it the default

**Comment by nop33** [comment]
Thanks for taking the time! I tried out the flow you mentioned and it seems to work fine... I'll keep testing.


https://github.com/alephium/mobile-wallet/assets/1579899/b63cd169-1cf2-42b8-add6-26ea4da97ef0

**Comment by nop33** [comment]
Thanks again! Indeed, I did not manage to reproduce (see my demo)


https://github.com/alephium/mobile-wallet/assets/1579899/91cbe39a-3fa5-469d-9669-c1d0f26e7eb8

**Comment by ErgoTester** [comment]
deleted , it was my bad it needed to be saved

**Comment by ErgoTester** [comment]
https://github.com/alephium/mobile-wallet/assets/134221896/a4a13b39-b9d1-4499-ab90-390679504e75

first 2 issues

**Comment by ErgoTester** [comment]
> deleted , it was my bad it needed to be saved

will add it again in a different way , since some settings were changed , if you go back , a pop up screen need to be shown "discard changes or save"

**Comment by diomark** [comment]
wallet connect isn't connecting , tried with ayin and deardare ( pc ) the wallet scan the qr than goes the home page , no message no warning no connection
 <-- this worked for me, but not the first time. I realized it was giving me a list of addresses to choose from. I had to select an address first then click approve, then it worked. (it was happily letting me click 'approve' and not selecting anything by default)

**Comment by ErgoTester** [comment]
yes got it working , might be connection issue
also tried it without having group 0 and wallet asked to create one which is cool

**Comment by ErgoTester** [comment]
@nop33 walletconnect not consistence, worked on on1 pc and not on other

**Comment by nop33** [comment]
All subtasks of this issue where either addressed or transferred to their own issues. Please, refer to them to track their progress! I'll close this one.
